service: serverless-aws-auth-solution
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  region: us-west-1
  projectName: serverless

custom:
  cognitoUserPoolName: ${self:provider.projectName}-user-pool-${self:provider.stage}
  mobileUserPoolClient: ${self:provider.projectName}-user-pool-client-mobile-${self:provider.stage}

resources:
  Resources:
    # COGNITO
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.cognitoUserPoolName}
        UsernameAttributes:
          - 'email'

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.mobileUserPoolClient}
        UserPoolId: !Ref CognitoUserPool

    CognitoUserGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        Description: 'Initial Users'
        GroupName: 'USER'
        Precedence: 1
        UserPoolId: !Ref CognitoUserPool

  Outputs:
    AwsCognitoUserPoolId:
      Description: 'Cognito User Pool Id'
      Value: !Ref CognitoUserPool
