service: serverless-aws-vpn-solution
frameworkVersion: '3'

custom:
  awsRegion: us-west-1
  sqsPrimaryKey: instanceId
  vpnStatelambdaFunctionName: syncVpnState
  startAndStopVpnInstanceLambdaFunctionName: startAndStopVpnInstance

  cognitoUserPoolName: vpn-user-pool
  mobileUserPoolClient: vpn-user-pool-client-mobile

  appSyncLambdaRole: app-sync-execute-lambda

  adminIAMRoleName: vpn-admin-group-role
  customerIAMRoleName: vpn-customer-group-role

  adminIAMRolePolicyName: vpn-admin-group-role-policy
  customerIAMRolePolicyName: vpn-customer-group-role-policy

  vpnStateTableName: vpn-table-${self:provider.stage}
  awsSyncGraphqlEndpoint: !GetAtt GraphQlApi.GraphQLUrl

  dynamodb:
    stages:
      - dev
    start:
      migrate: true

appSync:
  name: vpn-appsync-api-${self:provider.stage}
  authentication:
    type: AMAZON_COGNITO_USER_POOLS
    config:
      userPoolId: !Ref CognitoUserPool
  additionalAuthentications:
    - type: AWS_IAM

  resolvers:
    getVpnInstances:
      dataSource: VpnTable
      type: Query
      field: getVpnInstances
      functions:
        - scanVpnTable
    createOrUpdateVpnInstance:
      dataSource: VpnTable
      type: Mutation
      field: createOrUpdateVpnInstance
      functions:
        - putVpnInstance
    startVpnInstance:
      dataSource: AwsLambda
      type: Mutation
      field: startVpnInstance
      functions:
        - startOrStopVpnInstance
    stopVpnInstance:
      dataSource: AwsLambda
      type: Mutation
      field: stopVpnInstance
      functions:
        - startOrStopVpnInstance

  pipelineFunctions:
    scanVpnTable:
      dataSource: VpnTable
      code: resolvers/getVpnInstances.js

    putVpnInstance:
      dataSource: VpnTable
      code: resolvers/putVpnInstance.js

    startOrStopVpnInstance:
      dataSource: AwsLambda
      code: resolvers/startOrStopVpnInstance.js

  dataSources:
    VpnTable:
      type: AMAZON_DYNAMODB
      config:
        tableName: !Ref VpnTable
    AwsLambda:
      type: AWS_LAMBDA
      config:
        functionArn: { Fn::GetAtt: [StartAndStopVpnInstanceLambdaFunction, Arn] }
        serviceRoleArn: { Fn::GetAtt: [AppSyncExecuteLambdaRole, Arn] }

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ${self:custom.awsRegion}
  environment:
    GRAPHQL_AWS_REGION: ${self:custom.awsRegion}
    GRAPHQL_ENDPOINT: !GetAtt GraphQlApi.GraphQLUrl

plugins:
  - serverless-offline
  - serverless-export-env
  - serverless-appsync-plugin
  - serverless-dynamodb-local
  - serverless-iam-roles-per-function

functions:
  syncVpnState:
    name: ${self:custom.vpnStatelambdaFunctionName}
    handler: syncVpnStateLambda.handler
    events:
      - cloudwatchEvent:
          name: 'vpn-service-cloudwatch-event-on-ec2-instance-state-change'
          description: 'CloudWatch Event triggered on EC2 Instance pending state'
          event:
            source:
              - 'aws.ec2'
            detail-type:
              - 'EC2 Instance State-change Notification'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - appsync:GraphQL
        Resource:
          - {
              Fn::Join:
                [
                  '',
                  [
                    { Ref: GraphQlApi },
                    '/types/Mutation/fields/createOrUpdateVpnInstance',
                  ],
                ],
            }

  startAndStopVpnInstance:
    name: ${self:custom.startAndStopVpnInstanceLambdaFunctionName}
    handler: startAndStopVpnInstanceLambda.handler
    iamRoleStatementsName: 'lambda-start-stop-ec2'
    iamRoleStatements:
      - Effect: Allow
        Resource:
          - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*'
        Action:
          - 'ec2:Start*'
          - 'ec2:Stop*'

resources:
  Resources:
    VpnTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: ${self:custom.sqsPrimaryKey}
            AttributeType: S
        KeySchema:
          - AttributeName: ${self:custom.sqsPrimaryKey}
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.vpnStateTableName}

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.cognitoUserPoolName}
        UsernameAttributes:
          - 'email'

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.mobileUserPoolClient}
        UserPoolId: !Ref CognitoUserPool

    # User Pool Groups

    CognitoAdminGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        Description: 'Admin users belongs to this group'
        GroupName: 'Admin'
        Precedence: 0
        RoleArn:
          Fn::GetAtt: [CognitoAdminIAMRole, Arn]
        UserPoolId: !Ref CognitoUserPool

    CognitoCustomerGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        Description: 'Cusomer users belongs to this group'
        GroupName: 'Customer'
        Precedence: 1
        RoleArn:
          Fn::GetAtt: [CognitoUserIAMRole, Arn]
        UserPoolId: !Ref CognitoUserPool

    # IAM Roles
    CognitoAdminIAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.adminIAMRoleName}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Principal:
              Federated:
                - 'cognito-identity-amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
        Description: 'VPN Admin Group Policy'
        Policies:
          - PolicyName: ${self:custom.adminIAMRolePolicyName}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'dynamodb:*'
                  Resource:
                    Fn::GetAtt: [VpnTable, Arn]

    AppSyncExecuteLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.appSyncLambdaRole}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Principal:
              Service:
                - 'appsync.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
        Description: 'App Sync Policy to execute lambda'
        Policies:
          - PolicyName: awssync-invoke-lambda-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'lambda:InvokeFunction'
                    - 'lambda:InvokeAsync'
                  Resource:
                    - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:custom.startAndStopVpnInstanceLambdaFunctionName}'

    CognitoUserIAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.customerIAMRoleName}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Principal:
              Federated:
                - 'cognito-identity-amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
        Description: 'VPN Customer Group Policy'
        Policies:
          - PolicyName: ${self:custom.customerIAMRolePolicyName}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'dynamodb:*'
                  Resource:
                    Fn::GetAtt: [VpnTable, Arn]

  Outputs:
    AwsAppSyncRegion:
      Description: 'AppSync Region'
      Value: ${self:custom.awsRegion}
    AwsAppSyncAuthenticationType:
      Description: 'AppSync Primary Authentication Type'
      Value: AMAZON_COGNITO_USER_POOLS
    AwsAppSyncRealTimeGraphqlEndpoint:
      Description: 'AppSync Graphql Endpoint'
      Value: !GetAtt GraphQlApi.GraphQLUrl
    AwsAppSyncGraphqlEndpoint:
      Description: 'AppSync Graphql Reacltime Endpoint'
      Value: !GetAtt GraphQlApi.RealtimeUrl

    AwsCognitoRegion:
      Description: 'Cognito Region'
      Value: ${self:custom.awsRegion}

    AwsCognitoUserPoolId:
      Description: 'Cognito User Pool Id'
      Value: !Ref CognitoUserPool

    AwsCognitoUserPoolWebClientId:
      Description: 'Cognito Web Client Id'
      Value: !Ref CognitoUserPoolClient

    AwsCognitoMandatorySignIn:
      Description: 'Cognito Mandatory Sign In'
      Value: true
