service: serverless-aws-solution
frameworkVersion: '3'

custom:
  awsRegion: us-west-1
  dynamoTablePrimaryKey: instanceId
  vpnStatelambdaFunctionName: syncVpnState
  startAndStopVpnInstanceLambdaFunctionName: startAndStopVpnInstance

  cognitoUserPoolName: vpn-user-pool-${self:provider.stage}
  mobileUserPoolClient: vpn-user-pool-client-mobile-${self:provider.stage}

  appSyncLambdaRole: app-sync-execute-lambda-${self:provider.stage}

  adminIAMRoleName: vpn-admin-group-role-${self:provider.stage}
  customerIAMRoleName: vpn-customer-group-role-${self:provider.stage}

  adminIAMRolePolicyName: vpn-admin-group-role-policy-${self:provider.stage}
  customerIAMRolePolicyName: vpn-customer-group-role-policy-${self:provider.stage}

  vpnStateTableName: vpn-table-${self:provider.stage}-${self:provider.stage}
  awsSyncGraphqlEndpoint: !GetAtt GraphQlApi.GraphQLUrl

  # face rekognition
  ## lambda
  photoProcessorLambdaName: photoProcessorOnUpload-${self:provider.stage}
  basePhotoProcessorLambdaName: baseProcessorOnUpload-${self:provider.stage}

  ## s3
  s3PhotosBucket: 'krasovsky-family-photos-${self:provider.stage}'
  baseUploadFolder: 'baseUploads'
  baseProcessedFolder: 'baseProcessed'

  photoUploadFolder: 'photoUploads'
  processedPhotosFolder: 'photoUploadsProcessed'

  ## rekognition
  rekognitionCollectionId: 'family-rekognition-collection-${self:provider.stage}'

  ## dynamo db
  photosTable: family-photoes-${self:provider.stage}

  dynamodb:
    stages:
      - dev
    start:
      migrate: true

appSync:
  name: appsync-api-${self:provider.stage}
  authentication:
    type: AMAZON_COGNITO_USER_POOLS
    config:
      userPoolId: !Ref CognitoUserPool
  additionalAuthentications:
    - type: AWS_IAM

  resolvers:
    # queries
    getVpnInstances:
      dataSource: VpnTable
      type: Query
      field: getVpnInstances
      functions:
        - scanVpnTable

    getFaceBaseRekognitionsForPerson:
      dataSource: photosTable
      type: Query
      field: getFaceBaseRekognitionsForPerson
      functions:
        - getFaceBaseRekognitionsForPerson

    # mutations
    createOrUpdateVpnInstance:
      dataSource: VpnTable
      type: Mutation
      field: createOrUpdateVpnInstance
      functions:
        - putVpnInstance

    createFaceBaseRecognition:
      dataSource: photosTable
      type: Mutation
      field: createFaceBaseRecognition
      functions:
        - createFaceBaseRecognition

    createPerson:
      dataSource: photosTable
      type: Mutation
      field: createPerson
      functions:
        - createPersonFunction

    startVpnInstance:
      dataSource: AwsLambda
      type: Mutation
      field: startVpnInstance
      functions:
        - startOrStopVpnInstance

    stopVpnInstance:
      dataSource: AwsLambda
      type: Mutation
      field: stopVpnInstance
      functions:
        - startOrStopVpnInstance

  pipelineFunctions:
    # SCAN
    scanVpnTable:
      dataSource: VpnTable
      code: resolvers/vpnInstances/getVpnInstances.js

    getFaceBaseRekognitionsForPerson:
      dataSource: photosTable
      code: resolvers/photos/getFaceBaseRekognitionsForPerson.js

    # MUTATIONS
    putVpnInstance:
      dataSource: VpnTable
      code: resolvers/vpnInstances/putVpnInstance.js

    createPersonFunction:
      dataSource: photosTable
      code: resolvers/photos/createPerson.js

    createFaceBaseRecognition:
      dataSource: photosTable
      code: resolvers/photos/createFaceBaseRekognition.js

    startOrStopVpnInstance:
      dataSource: AwsLambda
      code: resolvers/vpnInstances/startOrStopVpnInstance.js

  dataSources:
    VpnTable:
      type: AMAZON_DYNAMODB
      config:
        tableName: !Ref VpnTable

    photosTable:
      type: AMAZON_DYNAMODB
      config:
        tableName: !Ref photosTable

    AwsLambda:
      type: AWS_LAMBDA
      config:
        functionArn:
          { Fn::GetAtt: [StartAndStopVpnInstanceLambdaFunction, Arn] }
        serviceRoleArn: { Fn::GetAtt: [AppSyncExecuteLambdaRole, Arn] }

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ${self:custom.awsRegion}
  environment:
    GRAPHQL_AWS_REGION: ${self:custom.awsRegion}
    #GRAPHQL_ENDPOINT: !GetAtt GraphQlApi.GraphQLUrl
    GRAPHQL_ENDPOINT: 'https://mpe7fmajevh7pbb7zt4mlwktk4.appsync-api.us-west-1.amazonaws.com/graphql'
    PHOTOS_S3_BUCKET: ${self:custom.s3PhotosBucket}
    PROCESSED_FOLDER: ${self:custom.processedPhotosFolder}
    BASE_PROCESSED_FOLDER: ${self:custom.baseProcessedFolder}
    REKOGNITION_COLLECTION_ID: ${self:custom.rekognitionCollectionId}

plugins:
  - serverless-offline
  - serverless-export-env
  - serverless-appsync-plugin
  - serverless-dynamodb-local
  - serverless-iam-roles-per-function

functions:
  syncVpnState:
    name: ${self:custom.vpnStatelambdaFunctionName}
    handler: lambdaSyncVpnState.handler
    events:
      - cloudwatchEvent:
          name: 'vpn-service-cloudwatch-event-on-ec2-instance-state-change'
          description: 'CloudWatch Event triggered on EC2 Instance pending state'
          event:
            source:
              - 'aws.ec2'
            detail-type:
              - 'EC2 Instance State-change Notification'
    iamRoleStatements:
      - Effect: Allow
        Action:
          - appsync:GraphQL
        Resource:
          - {
              Fn::Join:
                [
                  '',
                  [
                    { Ref: GraphQlApi },
                    '/types/Mutation/fields/createOrUpdateVpnInstance',
                  ],
                ],
            }

  startAndStopVpnInstance:
    name: ${self:custom.startAndStopVpnInstanceLambdaFunctionName}
    handler: lambdaStartAndStopVpnInstance.handler
    iamRoleStatementsName: 'lambda-start-stop-ec2'
    iamRoleStatements:
      - Effect: Allow
        Resource:
          - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*'
        Action:
          - 'ec2:Start*'
          - 'ec2:Stop*'

  processBasePhoto:
    name: ${self:custom.basePhotoProcessorLambdaName}
    handler: lambdaProcessUploadedBasePhoto.handler
    timeout: 60
    events:
      - s3:
          bucket: ${self:custom.s3PhotosBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: !Sub '${self:custom.baseUploadFolder}/'
          # existing: true
          # forceDeploy: true
    iamRoleStatements:
      # publish to amazon rekognition
      - Effect: Allow
        Action:
          - rekognition:IndexFaces
        Resource:
          - { Fn::GetAtt: [FaceRekognitionCollection, Arn] }
      # read/delete files from s3
      - Effect: Allow
        Action:
          - 's3:GetObject'
          - 's3:PutObject'
          - 's3:DeleteObject'
        Resource:
          - !Sub 'arn:aws:s3:::${self:custom.s3PhotosBucket}/*'
      # appSync Mutations
      - Effect: Allow
        Action:
          - appsync:GraphQL
        Resource:
          - {
              Fn::Join:
                [
                  '',
                  [
                    { Ref: GraphQlApi },
                    '/types/Mutation/fields/createFaceBaseRecognition',
                  ],
                ],
            }

  processUploadedPhoto:
    name: ${self:custom.photoProcessorLambdaName}
    handler: lambdaProcessUploadedFamilyPhoto.handler
    timeout: 60
    events:
      - s3:
          bucket: ${self:custom.s3PhotosBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: !Sub '${self:custom.photoUploadFolder}/'
          # existing: true
          # forceDeploy: true
    iamRoleStatements:
      # publish to amazon rekognition
      - Effect: Allow
        Action:
          - rekognition:DetectFaces
          - rekognition:SearchFacesByImage
        Resource:
          - { Fn::GetAtt: [FaceRekognitionCollection, Arn] }
      # read/delete files from s3
      - Effect: Allow
        Action:
          - 's3:GetObject'
          - 's3:PutObject'
          - 's3:DeleteObject'
        Resource:
          - !Sub 'arn:aws:s3:::${self:custom.s3PhotosBucket}/*'
      # appSync Mutations
      # - Effect: Allow
      #   Action:
      #     - appsync:GraphQL
      #   Resource:
      #     - {
      #         Fn::Join:
      #           [
      #             '',
      #             [
      #               { Ref: GraphQlApi },
      #               '/types/Mutation/fields/createFaceBaseRecognition',
      #             ],
      #           ],
      #       }

resources:
  Resources:
    # DYNAMO DB
    photosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.photosTable}

    VpnTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: ${self:custom.dynamoTablePrimaryKey}
            AttributeType: S
        KeySchema:
          - AttributeName: ${self:custom.dynamoTablePrimaryKey}
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.vpnStateTableName}

    # COGNITO
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.cognitoUserPoolName}
        UsernameAttributes:
          - 'email'

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.mobileUserPoolClient}
        UserPoolId: !Ref CognitoUserPool

    # User Pool Groups

    CognitoAdminGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        Description: 'Admin users belongs to this group'
        GroupName: 'Admin'
        Precedence: 0
        RoleArn:
          Fn::GetAtt: [CognitoAdminIAMRole, Arn]
        UserPoolId: !Ref CognitoUserPool

    CognitoCustomerGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        Description: 'Cusomer users belongs to this group'
        GroupName: 'Customer'
        Precedence: 1
        RoleArn:
          Fn::GetAtt: [CognitoUserIAMRole, Arn]
        UserPoolId: !Ref CognitoUserPool

    # IAM Roles
    CognitoAdminIAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.adminIAMRoleName}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Principal:
              Federated:
                - 'cognito-identity-amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
        Description: 'VPN Admin Group Policy'
        Policies:
          - PolicyName: ${self:custom.adminIAMRolePolicyName}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'dynamodb:*'
                  Resource:
                    Fn::GetAtt: [VpnTable, Arn]

    AppSyncExecuteLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.appSyncLambdaRole}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Principal:
              Service:
                - 'appsync.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
        Description: 'App Sync Policy to execute lambda'
        Policies:
          - PolicyName: awssync-invoke-lambda-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'lambda:InvokeFunction'
                    - 'lambda:InvokeAsync'
                  Resource:
                    - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:custom.startAndStopVpnInstanceLambdaFunctionName}'

    CognitoUserIAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.customerIAMRoleName}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Principal:
              Federated:
                - 'cognito-identity-amazonaws.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
        Description: 'VPN Customer Group Policy'
        Policies:
          - PolicyName: ${self:custom.customerIAMRolePolicyName}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'dynamodb:*'
                  Resource:
                    Fn::GetAtt: [VpnTable, Arn]

    FaceRekognitionCollection:
      Type: AWS::Rekognition::Collection
      Properties:
        CollectionId: ${self:custom.rekognitionCollectionId}


  Outputs:
    AwsAppSyncRegion:
      Description: 'AppSync Region'
      Value: ${self:custom.awsRegion}
    AwsAppSyncAuthenticationType:
      Description: 'AppSync Primary Authentication Type'
      Value: AMAZON_COGNITO_USER_POOLS
    AwsAppSyncRealTimeGraphqlEndpoint:
      Description: 'AppSync Graphql Endpoint'
      Value: !GetAtt GraphQlApi.GraphQLUrl
    AwsAppSyncGraphqlEndpoint:
      Description: 'AppSync Graphql Reacltime Endpoint'
      Value: !GetAtt GraphQlApi.RealtimeUrl

    AwsCognitoRegion:
      Description: 'Cognito Region'
      Value: ${self:custom.awsRegion}

    AwsCognitoUserPoolId:
      Description: 'Cognito User Pool Id'
      Value: !Ref CognitoUserPool

    AwsCognitoUserPoolWebClientId:
      Description: 'Cognito Web Client Id'
      Value: !Ref CognitoUserPoolClient

    AwsCognitoMandatorySignIn:
      Description: 'Cognito Mandatory Sign In'
      Value: true
